"""phase3 ethereum intelligence foundation

Revision ID: 6014276fbd67
Revises: 0002_execution_wallets
Create Date: 2026-08-06 00:04:36.375349
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6014276fbd67'
down_revision: str | None = '0002_execution_wallets'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chains',
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('namespace', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('currency_symbol', sa.String(length=16), nullable=False),
    sa.Column('finality_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chain_id = 1', name=op.f('ck_chains_release1_ethereum_mainnet')),
    sa.PrimaryKeyConstraint('chain_id', name=op.f('pk_chains'))
    )
    op.execute(
        "INSERT INTO chains "
        "(chain_id, namespace, name, currency_symbol, finality_configuration) VALUES "
        "(1, 'eip155', 'Ethereum mainnet', 'ETH', "
        "'{\"safe_tag\": \"safe\", \"finalized_tag\": \"finalized\", "
        "\"reorg_lookback\": 64}'::jsonb)"
    )
    op.create_table('chain_cursors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('last_processed_block_number', sa.BigInteger(), nullable=False),
    sa.Column('last_processed_block_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.chain_id'], name=op.f('fk_chain_cursors_chain_id_chains'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chain_cursors')),
    sa.UniqueConstraint('chain_id', 'purpose', name=op.f('uq_chain_cursors_chain_id'))
    )
    op.create_table('collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('normalized_address', sa.String(length=42), nullable=False),
    sa.Column('checksum_address', sa.String(length=42), nullable=False),
    sa.Column('token_standard', sa.Enum('erc721', 'erc1155', 'erc2309', 'custom', 'unknown', name='token_standard', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('deployment_block_number', sa.BigInteger(), nullable=True),
    sa.Column('deployment_block_hash', sa.LargeBinary(length=32), nullable=True),
    sa.Column('deployment_confidence', sa.Enum('exact', 'bounded', 'unknown', name='deployment_confidence', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('deployment_confidence_value', sa.SmallInteger(), nullable=False),
    sa.Column('scan_status', sa.Enum('pending', 'scanning', 'complete', 'failed', 'quality_warning', name='collection_scan_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('deployment_confidence_value BETWEEN 0 AND 100', name=op.f('ck_collections_deployment_confidence_range')),
    sa.CheckConstraint('length(normalized_address) = 42', name=op.f('ck_collections_address_length')),
    sa.CheckConstraint('normalized_address = lower(normalized_address)', name=op.f('ck_collections_normalized_address')),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.chain_id'], name=op.f('fk_collections_chain_id_chains'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('chain_id', 'normalized_address', name=op.f('uq_collections_chain_id'))
    )
    op.create_index('ix_collections_scan_status', 'collections', ['chain_id', 'scan_status'], unique=False)
    op.create_table('raw_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('block', 'log', 'transaction', 'receipt', 'trace', name='evidence_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('content_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('provider_alias', sa.String(length=64), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('transaction_hash', sa.LargeBinary(length=32), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retention_status', sa.Enum('active', 'archived', 'expired', name='evidence_retention_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('octet_length(content_hash) = 32', name=op.f('ck_raw_evidence_sha256_content_hash')),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.chain_id'], name=op.f('fk_raw_evidence_chain_id_chains'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_evidence')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_raw_evidence_content_hash'))
    )
    op.create_index('ix_raw_evidence_chain_kind', 'raw_evidence', ['chain_id', 'kind'], unique=False)
    op.execute(
        "CREATE FUNCTION reject_raw_evidence_mutation() RETURNS trigger AS $$ "
        "BEGIN RAISE EXCEPTION 'raw evidence is immutable'; END; "
        "$$ LANGUAGE plpgsql"
    )
    op.execute(
        "CREATE TRIGGER raw_evidence_immutable BEFORE UPDATE OR DELETE ON raw_evidence "
        "FOR EACH ROW EXECUTE FUNCTION reject_raw_evidence_mutation()"
    )
    op.create_table('collection_implementations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('implementation_address', sa.String(length=42), nullable=False),
    sa.Column('effective_from_block', sa.BigInteger(), nullable=False),
    sa.Column('effective_to_block', sa.BigInteger(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('effective_to_block IS NULL OR effective_to_block >= effective_from_block', name=op.f('ck_collection_implementations_implementation_block_interval')),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_implementations_collection_id_collections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_implementations')),
    sa.UniqueConstraint('collection_id', 'effective_from_block', name=op.f('uq_collection_implementations_collection_id'))
    )
    op.create_table('mint_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('raw_evidence_id', sa.Uuid(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('transaction_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('sub_index', sa.Integer(), nullable=False),
    sa.Column('token_standard', sa.Enum('erc721', 'erc1155', 'erc2309', 'custom', 'unknown', name='mint_event_token_standard', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('token_id', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('recipient', sa.String(length=42), nullable=False),
    sa.Column('transaction_sender', sa.String(length=42), nullable=True),
    sa.Column('operator', sa.String(length=42), nullable=True),
    sa.Column('payer', sa.String(length=42), nullable=True),
    sa.Column('probable_initiator', sa.String(length=42), nullable=True),
    sa.Column('identity_confidence', sa.SmallInteger(), nullable=False),
    sa.Column('identity_reason_code', sa.String(length=64), nullable=False),
    sa.Column('route', sa.Enum('direct', 'seadrop', 'launchpad', 'marketplace', 'relayer', 'unknown', name='mint_event_route', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('classification', sa.Enum('public_paid_mint', 'public_free_mint', 'allowlist_mint', 'token_gated_mint', 'server_signed_mint', 'admin_mint', 'airdrop', 'bridge_mint', 'migration_mint', 'lazy_marketplace_mint', 'unknown_mint', name='mint_event_classification', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('classification_reason_code', sa.String(length=64), nullable=False),
    sa.Column('finality', sa.Enum('provisional', 'safe', 'finalized', 'reorged', name='mint_event_finality', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('canonical', sa.Boolean(), nullable=False),
    sa.CheckConstraint('identity_confidence BETWEEN 0 AND 100', name=op.f('ck_mint_events_identity_confidence_range')),
    sa.CheckConstraint('log_index >= 0 AND sub_index >= 0', name=op.f('ck_mint_events_nonnegative_log_position')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_mint_events_positive_quantity')),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.chain_id'], name=op.f('fk_mint_events_chain_id_chains'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_mint_events_collection_id_collections'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_evidence_id'], ['raw_evidence.id'], name=op.f('fk_mint_events_raw_evidence_id_raw_evidence'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mint_events')),
    sa.UniqueConstraint('chain_id', 'transaction_hash', 'log_index', 'sub_index', name=op.f('uq_mint_events_chain_id'))
    )
    op.create_index('ix_mint_events_collection_block', 'mint_events', ['collection_id', 'block_number'], unique=False)
    op.create_index('ix_mint_events_initiator', 'mint_events', ['chain_id', 'probable_initiator'], unique=False)
    op.create_table('scan_checkpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('scan_version', sa.Integer(), nullable=False),
    sa.Column('last_committed_block_number', sa.BigInteger(), nullable=False),
    sa.Column('last_committed_block_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_scan_checkpoints_collection_id_collections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_checkpoints')),
    sa.UniqueConstraint('collection_id', 'scan_version', name=op.f('uq_scan_checkpoints_collection_id'))
    )
    op.create_table('scan_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('scan_version', sa.Integer(), nullable=False),
    sa.Column('start_block', sa.BigInteger(), nullable=False),
    sa.Column('end_block', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'cancelled', name='scan_job_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('quality_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_scan_jobs_nonnegative_attempt_count')),
    sa.CheckConstraint('start_block >= 0 AND end_block >= start_block', name=op.f('ck_scan_jobs_valid_block_range')),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_scan_jobs_collection_id_collections'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_jobs')),
    sa.UniqueConstraint('collection_id', 'scan_version', name=op.f('uq_scan_jobs_collection_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_jobs')
    op.drop_table('scan_checkpoints')
    op.drop_index('ix_mint_events_initiator', table_name='mint_events')
    op.drop_index('ix_mint_events_collection_block', table_name='mint_events')
    op.drop_table('mint_events')
    op.drop_table('collection_implementations')
    op.execute("DROP FUNCTION IF EXISTS reject_raw_evidence_mutation()")
    op.drop_index('ix_raw_evidence_chain_kind', table_name='raw_evidence')
    op.drop_table('raw_evidence')
    op.drop_index('ix_collections_scan_status', table_name='collections')
    op.drop_table('collections')
    op.drop_table('chain_cursors')
    op.drop_table('chains')
    # ### end Alembic commands ###
